/* AUTO-GENERATED từ survey-schema.js — chạy: node generate-columns.js */
const COLUMNS = [
  'timestamp','duration_sec','version','source','Q1','Q2',
  'Q3','Q4','Q5','Q6','Q7','Q8',
  'Q9','Q10','Q10a','Q10b','Q11_gps','Q11_sos',
  'Q11_zone','Q11_call','Q11_habit','Q11_app','Q11_ai','Q11_passport',
  'Q11','Q11a','Q12','Q13_condition','Q13_repair','Q13_warranty','Q13_wipe',
  'Q13_age','Q13_origin','Q13','Q14','Q15','Q16',
  'Q17','Q18','Q19','Q20'
];

const HEADERS_VI = {
  timestamp: 'Thời gian',
  duration_sec: 'Thời lượng (giây)',
  version: 'Phiên bản',
  source: 'Nguồn',
  Q1: 'S1-Hồ sơ-Tuổi con',
  Q2: 'S1-Hồ sơ-Tuổi PH',
  Q3: 'S1-Hồ sơ-Người quyết định mua',
  Q4: 'S1-Hồ sơ-Thu nhập',
  Q5: 'S1-Hồ sơ-Thiết bị đang dùng',
  Q6: 'S2-Nỗi lo-Mức lo lắng',
  Q7: 'S2-Nỗi lo-Tình huống lo nhất',
  Q8: 'S2-Nỗi lo-Lo ngại khi cho trẻ dùng smartphone',
  Q9: 'S3-Hiện trạng-Cách liên lạc',
  Q10: 'S3-Hiện trạng-Kinh nghiệm smartwatch',
  Q10a: 'S3-Hiện trạng-Lý do mua',
  Q10b: 'S3-Hiện trạng-Lý do chưa mua',
  Q11_gps: 'S4-Tính năng-Ma trận tính năng: Định vị GPS thời gian thực',
  Q11_sos: 'S4-Tính năng-Ma trận tính năng: Nút SOS khẩn cấp',
  Q11_zone: 'S4-Tính năng-Ma trận tính năng: Vùng an toàn (Safe Zone)',
  Q11_call: 'S4-Tính năng-Ma trận tính năng: Gọi điện 2 chiều giới hạn danh bạ',
  Q11_habit: 'S4-Tính năng-Ma trận tính năng: Nhiệm vụ & đổi xu (rèn thói quen)',
  Q11_app: 'S4-Tính năng-Ma trận tính năng: Ứng dụng cho phụ huynh (Parent App)',
  Q11_ai: 'S4-Tính năng-Ma trận tính năng: Trợ lý AI hỗ trợ khách hàng',
  Q11_passport: 'S4-Tính năng-Ma trận tính năng: Hộ chiếu thiết bị (xem lịch sử & tình trạng máy)',
  Q11: 'S4-Tính năng-Ma trận tính năng (JSON)',
  Q11a: 'S4-Tính năng-Top 3 tính năng ưu tiên',
  Q12: 'S5-Đánh giá-Hữu ích',
  Q13_condition: 'S6-Tái sử dụng-Ma trận thông tin máy cũ: Tình trạng kỹ thuật hiện tại',
  Q13_repair: 'S6-Tái sử dụng-Ma trận thông tin máy cũ: Lịch sử sửa chữa / thay linh kiện',
  Q13_warranty: 'S6-Tái sử dụng-Ma trận thông tin máy cũ: Còn bảo hành hay không',
  Q13_wipe: 'S6-Tái sử dụng-Ma trận thông tin máy cũ: Đã xóa sạch dữ liệu chưa',
  Q13_age: 'S6-Tái sử dụng-Ma trận thông tin máy cũ: Thiết bị đã dùng bao lâu',
  Q13_origin: 'S6-Tái sử dụng-Ma trận thông tin máy cũ: Nguồn gốc / chính hãng thu hồi',
  Q13: 'S6-Tái sử dụng-Ma trận thông tin máy cũ (JSON)',
  Q14: 'S6-Tái sử dụng-Chênh lệch giá',
  Q15: 'S6-Tái sử dụng-Sẵn sàng Trade-in',
  Q16: 'S7-Giá-WTP hardware',
  Q17: 'S7-Giá-Phí Premium',
  Q18: 'S8-Riêng tư-Lo dữ liệu vị trí',
  Q19: 'S9-Mua-PURCHASE INTENTION',
  Q20: 'S9-Mua-Lý do không mua'
};
